name: 'dbtlings_01'
version: '1.0.0'
config-version: 2

profile: 'dbtlings'

model-paths: ["models"]
seed-paths: ["data"] # 簡易化のため seed として扱う（read_csv_auto も使えるが seed の方が debug しやすい）
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbtlings_01:
    materialized: view
