version: 2

models:
  - name: dim_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
      - name: email
        tests:
          - not_null
      - name: user_key
        tests:
          # TODO: dbt_utils のテストを1つ追加してください（例: not_null 以外でもOK）
          - not_null

