version: 2

models:
  - name: fct_order_totals
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: fees_usd
        tests:
          - not_null
      - name: total_before_tax_usd
        tests:
          - not_null
      - name: total_after_tax_usd
        tests:
          - not_null

